version: "3.9"

services:
  user-service:
    image: ${USER_SERVICE_IMAGE}
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://<POSTGRES_HOST>:5432/userdb
      SPRING_DATASOURCE_USERNAME: <POSTGRES_USER>
      SPRING_DATASOURCE_PASSWORD: <POSTGRES_PASSWORD>

  product-service:
    image: ${PRODUCT_SERVICE_IMAGE}
    container_name: product-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://<POSTGRES_HOST>:5432/productdb
      SPRING_DATASOURCE_USERNAME: <POSTGRES_USER>
      SPRING_DATASOURCE_PASSWORD: <POSTGRES_PASSWORD>

  order-service:
    image: ${ORDER_SERVICE_IMAGE}
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://<POSTGRES_HOST>:5432/orderdb
      SPRING_DATASOURCE_USERNAME: <POSTGRES_USER>
      SPRING_DATASOURCE_PASSWORD: <POSTGRES_PASSWORD>
